---
name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install
        run: cd parser; make install
      - name: Build parser
        run: cd parser; make build
      - name: Build sender
        run: cd sender; make build
      - name: Upload parser
        uses: actions/upload-artifact@v2
        with:
          name: parser-x86_64-unknown-linux-musl
          path: parser/target/x86_64-unknown-linux-musl/release/parser
      - name: Upload sender
        uses: actions/upload-artifact@v2
        with:
          name: sender-x86_64-unknown-linux-musl
          path: sender/target/x86_64-unknown-linux-musl/release/sender
